### PR TITLE
Info list search

### PR DESCRIPTION
**Pull request by jakmeier**

### CODE REVIEW

**Comment by jakmeier** [comment]
I was a bit busier than expected lately... But today finally a first suggestion for the implementation of #53. :)

So far I have implemented a basic search. Things I might want to improve later:
* Smooth slide-in animation when opening the search bar.
* Maybe the full list should be shown when the search bar is closed but a keyword is still stored. I'm not quite sure, yet, what the best UX is here.

Also, I'm not experienced with React Native (or React) but I am open to learn best practices etc. So please add any comments how things could be improved or how you would structure it differently.

**Comment by jakmeier** [comment]
I think this is ready for review, basic search works the way I understood it should. And the animation also looks ok in my opinion.

**Comment by jakmeier** [comment]
@demianh Habe hier noch die Suche etwas angepasst. Der Suchstate wird zurückgesetzt beim Kontextwechsel und ein "X" fürs Löschen erscheint jetzt recht von der Suche.
Beim Icon war ich nicht sicher, ich finde das 'close' X passt nicht perfekt, aber wusste nicht was sonst.

**Comment by demianh** [comment]
Hab noch ein paar Designanpassungen gemacht und gleich gemerged! Danke :)

**Pull request merged**
